name: Update Records from Pak gov website

on:
  schedule:
    - cron:  '0 4,5,10 * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get working copy
        uses: actions/checkout@master
        with:
          fetch-depth: 1                                                                 
      - name: Set up Python 3.8                               
        uses: actions/setup-python@v2                               
        with:                                 
          python-version: '3.8'                                                   
      - name: Install Requirements                             
        run: pip install -r requirements.txt
      - name: Update dataset
        run: python Countries/Pakistan/covid19_pk_official.py
      - name: Update summery dataset
        run: python Countries/Pakistan/today.py
      - name: Export cases for forecast
        run: python Countries/Pakistan/refactor.py
      - name: Make Prediction
        run: python Countries/Pakistan/predict.py
      - name: Export from sqlite to CSV
        run: python Countries/Pakistan/toCsv.py
      - name: Export from CSV to JavaScript JSON
        run: python Countries/Pakistan/toJs.py
      - name: Update JavaScript file versions in HTML
        run: python updateJsVersions.py
      - name: Commit and push if it changed
        run: |
          git config user.name "AlphaSoftHub"
          git config user.email "alphasofthub@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Last Commit: ${timestamp}" || exit 0
          git push origin master
