name: Update Records from Pak gov website

on:
  schedule:
    - cron:  '0 6 * * *'
  workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get working copy
        uses: actions/checkout@master
        with:
          fetch-depth: 1                                                                 
      - name: Set up Python 3.8                               
        uses: actions/setup-python@v2                               
        with:                                 
          python-version: '3.8'                                                   
      - name: Install Requirements                             
        run: pip install -r requirements.txt
      - name: Update dataset
        run: python covid19_pk_official.py
      - name: Update summery dataset
        run: python today.py
      - name: Export from sqlite to CSV
        run: python toCsv.py
      - name: Commit and push if it changed
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Last Commit: ${timestamp}" || exit 0
          git push origin master
